CREATE TABLE `active_connections` (
  `id` varchar(255) NOT NULL,
  `client_id` varchar(255) DEFAULT NULL,
  `server_endpoint` varchar(255) DEFAULT NULL,
  `connected_at` datetime DEFAULT current_timestamp(),
  `last_activity` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `session_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`session_data`)),
  PRIMARY KEY (`id`),
  KEY `idx_client_id` (`client_id`),
  KEY `idx_last_activity` (`last_activity`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
CREATE TABLE `api_keys` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `key_name` varchar(100) NOT NULL,
  `api_key` varchar(64) NOT NULL,
  `user_id` int(11) DEFAULT NULL,
  `permissions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`permissions`)),
  `rate_limit` int(11) DEFAULT 1000,
  `requests_today` int(11) DEFAULT 0,
  `last_used` datetime DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT 1,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `api_key` (`api_key`),
  KEY `user_id` (`user_id`),
  KEY `idx_api_keys_key` (`api_key`),
  CONSTRAINT `api_keys_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `authorized_links` (
  `id` varchar(255) NOT NULL,
  `client_id` varchar(255) NOT NULL,
  `target_server` varchar(255) DEFAULT NULL,
  `link_type` enum('admin','desktop','fallback') NOT NULL,
  `authorized_at` datetime DEFAULT current_timestamp(),
  `authorized_by` varchar(255) DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT 1,
  `permissions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`permissions`)),
  `last_used` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_client_id` (`client_id`),
  KEY `idx_active` (`is_active`),
  KEY `idx_expires` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
CREATE TABLE `auto_link_requests` (
  `id` varchar(255) NOT NULL,
  `requesting_client_id` varchar(255) NOT NULL,
  `target_server` varchar(255) DEFAULT NULL,
  `request_type` enum('admin_auth','desktop_auth','server_fallback') NOT NULL,
  `status` enum('pending','approved','denied','expired') DEFAULT 'pending',
  `requested_at` datetime DEFAULT current_timestamp(),
  `processed_at` datetime DEFAULT NULL,
  `processed_by` varchar(255) DEFAULT NULL,
  `auto_approved` tinyint(1) DEFAULT 0,
  `approval_reason` text DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  PRIMARY KEY (`id`),
  KEY `idx_requesting_client` (`requesting_client_id`),
  KEY `idx_status` (`status`),
  KEY `idx_expires` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
CREATE TABLE `auto_provisioning_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `extension` varchar(10) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `action` varchar(50) NOT NULL,
  `details` text DEFAULT NULL,
  `status` enum('success','failed','pending') DEFAULT 'pending',
  `error_message` text DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL COMMENT 'Admin user ID who performed action',
  `timestamp` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_extension` (`extension`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_action` (`action`),
  KEY `idx_timestamp` (`timestamp`),
  KEY `idx_provisioning_log_lookup` (`extension`,`action`,`status`,`timestamp`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `backups` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `backup_name` varchar(255) NOT NULL,
  `backup_type` enum('full','database','config') NOT NULL,
  `file_path` varchar(500) DEFAULT NULL,
  `file_size` bigint(20) DEFAULT NULL,
  `status` enum('creating','completed','failed') DEFAULT 'creating',
  `created_by` int(11) DEFAULT NULL,
  `compression_type` varchar(20) DEFAULT 'gzip',
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `completed_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `created_by` (`created_by`),
  CONSTRAINT `backups_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `calendar_events` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `event_type` enum('meeting','call','reminder','appointment','holiday','dnd') DEFAULT 'call',
  `title` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `start_time` datetime NOT NULL,
  `end_time` datetime NOT NULL,
  `all_day` tinyint(1) DEFAULT 0,
  `timezone` varchar(50) DEFAULT 'America/Chicago',
  `recurring` tinyint(1) DEFAULT 0,
  `recurrence_pattern` enum('daily','weekly','monthly','yearly') DEFAULT NULL,
  `recurrence_end` date DEFAULT NULL,
  `owner_extension` varchar(20) DEFAULT NULL,
  `attendee_extensions` text DEFAULT NULL,
  `contact_id` int(11) DEFAULT NULL,
  `call_handling` enum('normal','dnd','forward','voicemail') DEFAULT 'normal',
  `forward_to` varchar(50) DEFAULT NULL,
  `reminder_enabled` tinyint(1) DEFAULT 0,
  `reminder_minutes` int(11) DEFAULT 15,
  `status` enum('pending','confirmed','cancelled','completed') DEFAULT 'pending',
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_owner` (`owner_extension`),
  KEY `idx_start` (`start_time`),
  KEY `idx_contact` (`contact_id`),
  CONSTRAINT `calendar_events_ibfk_1` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Calendar and scheduling system';
CREATE TABLE `call_history` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniqueid` varchar(100) DEFAULT NULL,
  `linkedid` varchar(100) DEFAULT NULL,
  `call_date` timestamp NULL DEFAULT current_timestamp(),
  `call_type` enum('inbound','outbound','internal','missed') NOT NULL,
  `caller_number` varchar(50) DEFAULT NULL,
  `caller_name` varchar(100) DEFAULT NULL,
  `caller_id_matched` tinyint(1) DEFAULT 0,
  `contact_id` int(11) DEFAULT NULL,
  `called_number` varchar(50) DEFAULT NULL,
  `called_name` varchar(100) DEFAULT NULL,
  `destination_extension` varchar(20) DEFAULT NULL,
  `status` enum('answered','no-answer','busy','failed','voicemail') DEFAULT 'no-answer',
  `disposition` varchar(50) DEFAULT NULL,
  `duration` int(11) DEFAULT 0,
  `billsec` int(11) DEFAULT 0,
  `context` varchar(80) DEFAULT NULL,
  `trunk` varchar(100) DEFAULT NULL,
  `recording_file` varchar(255) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniqueid` (`uniqueid`),
  KEY `idx_date` (`call_date`),
  KEY `idx_caller` (`caller_number`),
  KEY `idx_destination` (`destination_extension`),
  KEY `idx_contact` (`contact_id`),
  KEY `idx_type` (`call_type`),
  CONSTRAINT `call_history_ibfk_1` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Call history with caller ID matching';
CREATE TABLE `call_queues` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `queue_number` varchar(20) NOT NULL COMMENT 'Queue extension number',
  `queue_name` varchar(100) NOT NULL,
  `strategy` enum('ringall','leastrecent','fewestcalls','random','rrmemory','linear','wrandom') DEFAULT 'ringall',
  `timeout` int(11) DEFAULT 15 COMMENT 'Ring time per member (seconds)',
  `retry` int(11) DEFAULT 5 COMMENT 'Seconds between retries',
  `max_wait_time` int(11) DEFAULT 0 COMMENT 'Max wait time (0=unlimited)',
  `max_callers` int(11) DEFAULT 0 COMMENT 'Max callers in queue (0=unlimited)',
  `announce_frequency` int(11) DEFAULT 90 COMMENT 'Announcement interval (seconds)',
  `announce_position` enum('yes','no','limit','more') DEFAULT 'yes',
  `announce_holdtime` enum('yes','no','once') DEFAULT 'yes',
  `music_class` varchar(50) DEFAULT 'default',
  `join_announcement` varchar(255) DEFAULT NULL,
  `periodic_announce` text DEFAULT NULL COMMENT 'Comma-separated announcement files',
  `periodic_announce_frequency` int(11) DEFAULT 0,
  `callback_enabled` tinyint(1) DEFAULT 0,
  `auto_pause` enum('yes','no','all') DEFAULT 'no',
  `autopause_delay` int(11) DEFAULT 0,
  `wrap_up_time` int(11) DEFAULT 0 COMMENT 'Time after call before next call',
  `service_level` int(11) DEFAULT 60 COMMENT 'Service level threshold (seconds)',
  `enabled` tinyint(1) DEFAULT 1,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `queue_number` (`queue_number`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `call_records` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `call_id` varchar(128) NOT NULL,
  `caller_extension` varchar(10) DEFAULT NULL,
  `caller_number` varchar(50) DEFAULT NULL,
  `called_extension` varchar(10) DEFAULT NULL,
  `called_number` varchar(50) DEFAULT NULL,
  `call_direction` enum('inbound','outbound','internal') NOT NULL,
  `call_status` enum('answered','busy','no_answer','failed') NOT NULL,
  `start_time` datetime NOT NULL,
  `answer_time` datetime DEFAULT NULL,
  `end_time` datetime DEFAULT NULL,
  `duration` int(11) DEFAULT 0,
  `billable_duration` int(11) DEFAULT 0,
  `recording_file` varchar(255) DEFAULT NULL,
  `cost` decimal(10,4) DEFAULT 0.0000,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `call_id` (`call_id`),
  KEY `idx_call_records_time` (`start_time`),
  KEY `idx_call_records_caller` (`caller_extension`),
  KEY `idx_call_records_called` (`called_extension`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `call_screening` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `phone_number` varchar(20) NOT NULL,
  `screening_type` enum('blacklist','whitelist','spam') DEFAULT 'blacklist',
  `reason` varchar(255) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `action` enum('block','send_to_voicemail','play_message','forward') DEFAULT 'block',
  `action_data` varchar(255) DEFAULT NULL,
  `apply_to_extension` varchar(20) DEFAULT NULL,
  `apply_globally` tinyint(1) DEFAULT 0,
  `enabled` tinyint(1) DEFAULT 1,
  `hit_count` int(11) DEFAULT 0,
  `last_hit` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_number_extension` (`phone_number`,`apply_to_extension`),
  KEY `idx_type` (`screening_type`),
  KEY `idx_extension` (`apply_to_extension`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Call screening blacklist/whitelist';
CREATE TABLE `callerid_cache` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `phone_number` varchar(20) NOT NULL,
  `caller_name` varchar(100) DEFAULT NULL,
  `source` enum('contact','cnam','api','manual') DEFAULT 'contact',
  `verified` tinyint(1) DEFAULT 0,
  `last_verified` timestamp NULL DEFAULT NULL,
  `lookup_count` int(11) DEFAULT 0,
  `last_lookup` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `expires_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `phone_number` (`phone_number`),
  KEY `idx_phone` (`phone_number`),
  KEY `idx_source` (`source`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Caller ID name lookup cache';
CREATE TABLE `conferences` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `conference_number` varchar(20) NOT NULL,
  `conference_name` varchar(100) NOT NULL,
  `pin` varchar(20) DEFAULT NULL,
  `admin_pin` varchar(20) DEFAULT NULL,
  `max_participants` int(11) DEFAULT 50,
  `current_participants` int(11) DEFAULT 0,
  `recording_enabled` tinyint(1) DEFAULT 0,
  `is_active` tinyint(1) DEFAULT 1,
  `created_by` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `conference_number` (`conference_number`),
  KEY `created_by` (`created_by`),
  CONSTRAINT `conferences_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `connection_limits` (
  `client_type` enum('admin','desktop') NOT NULL,
  `default_max_connections` int(11) DEFAULT 1,
  `premium_max_connections` int(11) DEFAULT 5,
  `enterprise_max_connections` int(11) DEFAULT 50,
  `requires_approval` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`client_type`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
CREATE TABLE `contact_group_members` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `group_id` int(11) NOT NULL,
  `contact_id` int(11) NOT NULL,
  `added_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_group_contact` (`group_id`,`contact_id`),
  KEY `contact_id` (`contact_id`),
  CONSTRAINT `contact_group_members_ibfk_1` FOREIGN KEY (`group_id`) REFERENCES `contact_groups` (`id`) ON DELETE CASCADE,
  CONSTRAINT `contact_group_members_ibfk_2` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `contact_groups` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `group_name` varchar(100) NOT NULL,
  `description` text DEFAULT NULL,
  `owner_extension` varchar(20) DEFAULT NULL,
  `shared` tinyint(1) DEFAULT 0,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_group_owner` (`group_name`,`owner_extension`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `contact_phone_numbers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `contact_id` int(11) NOT NULL,
  `phone_number` varchar(20) NOT NULL,
  `phone_type` enum('primary','mobile','work','home','fax','other') DEFAULT 'primary',
  `formatted_number` varchar(30) DEFAULT NULL,
  `country_code` varchar(5) DEFAULT '+1',
  `extension` varchar(10) DEFAULT NULL,
  `is_primary` tinyint(1) DEFAULT 0,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_contact_phone` (`contact_id`,`phone_number`),
  KEY `idx_phone_lookup` (`phone_number`),
  KEY `idx_contact` (`contact_id`),
  CONSTRAINT `contact_phone_numbers_ibfk_1` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Normalized phone numbers for fast lookup';
CREATE TABLE `contacts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `contact_type` enum('personal','business','emergency','blacklist','whitelist') DEFAULT 'personal',
  `first_name` varchar(100) DEFAULT NULL,
  `last_name` varchar(100) DEFAULT NULL,
  `company` varchar(200) DEFAULT NULL,
  `title` varchar(100) DEFAULT NULL,
  `department` varchar(100) DEFAULT NULL,
  `primary_phone` varchar(20) DEFAULT NULL,
  `mobile_phone` varchar(20) DEFAULT NULL,
  `work_phone` varchar(20) DEFAULT NULL,
  `home_phone` varchar(20) DEFAULT NULL,
  `fax_phone` varchar(20) DEFAULT NULL,
  `other_phone` varchar(20) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `website` varchar(255) DEFAULT NULL,
  `address_line1` varchar(255) DEFAULT NULL,
  `address_line2` varchar(255) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `state` varchar(50) DEFAULT NULL,
  `zip` varchar(20) DEFAULT NULL,
  `country` varchar(100) DEFAULT 'USA',
  `notes` text DEFAULT NULL,
  `tags` varchar(500) DEFAULT NULL,
  `photo_url` varchar(255) DEFAULT NULL,
  `override_callerid` tinyint(1) DEFAULT 0,
  `custom_callerid_name` varchar(100) DEFAULT NULL,
  `custom_callerid_number` varchar(20) DEFAULT NULL,
  `speed_dial` varchar(10) DEFAULT NULL,
  `ring_tone` varchar(100) DEFAULT NULL,
  `call_recording` tinyint(1) DEFAULT 0,
  `forward_to_extension` varchar(20) DEFAULT NULL,
  `owner_extension` varchar(20) DEFAULT NULL,
  `shared` tinyint(1) DEFAULT 0,
  `status` enum('active','inactive','blocked') DEFAULT 'active',
  `favorite` tinyint(1) DEFAULT 0,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `last_called` timestamp NULL DEFAULT NULL,
  `call_count` int(11) DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_owner` (`owner_extension`),
  KEY `idx_phones` (`primary_phone`,`mobile_phone`,`work_phone`),
  KEY `idx_company` (`company`),
  KEY `idx_status` (`status`),
  KEY `idx_type` (`contact_type`),
  FULLTEXT KEY `idx_search` (`first_name`,`last_name`,`company`,`notes`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Contact Management System';
CREATE TABLE `desktop_clients` (
  `id` varchar(255) NOT NULL,
  `client_type` enum('admin','desktop') NOT NULL,
  `device_id` varchar(255) NOT NULL,
  `device_name` varchar(255) DEFAULT NULL,
  `platform` varchar(50) DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` text DEFAULT NULL,
  `first_connected` datetime DEFAULT current_timestamp(),
  `last_connected` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `is_active` tinyint(1) DEFAULT 1,
  `max_connections` int(11) DEFAULT 1,
  `current_connections` int(11) DEFAULT 0,
  `capabilities` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`capabilities`)),
  `settings` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`settings`)),
  PRIMARY KEY (`id`),
  KEY `idx_device_id` (`device_id`),
  KEY `idx_client_type` (`client_type`),
  KEY `idx_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
CREATE TABLE `devices` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `device_name` varchar(100) NOT NULL,
  `device_type` enum('desktop_mac','desktop_windows','flexphone_mobile','flexphone_desktop','sip_phone') NOT NULL,
  `user_id` int(11) DEFAULT NULL,
  `extension_id` int(11) DEFAULT NULL,
  `device_identifier` varchar(255) DEFAULT NULL,
  `pincode` varchar(6) DEFAULT NULL,
  `pincode_expires` datetime DEFAULT NULL,
  `last_connected` datetime DEFAULT NULL,
  `connection_ip` varchar(45) DEFAULT NULL,
  `is_authorized` tinyint(1) DEFAULT 0,
  `is_active` tinyint(1) DEFAULT 1,
  `device_info` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`device_info`)),
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `device_identifier` (`device_identifier`),
  KEY `extension_id` (`extension_id`),
  KEY `idx_devices_user` (`user_id`),
  KEY `idx_devices_type` (`device_type`),
  KEY `idx_devices_pincode` (`pincode`),
  CONSTRAINT `devices_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `devices_ibfk_2` FOREIGN KEY (`extension_id`) REFERENCES `extensions` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `did_request_queue` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `extension` varchar(10) NOT NULL,
  `requested_area_code` varchar(10) DEFAULT NULL,
  `request_type` enum('new','port','toll_free') DEFAULT 'new',
  `port_from_carrier` varchar(100) DEFAULT NULL,
  `port_number` varchar(20) DEFAULT NULL,
  `status` enum('pending','approved','processing','completed','rejected') DEFAULT 'pending',
  `assigned_did` varchar(20) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `processed_by` int(11) DEFAULT NULL,
  `processed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_extension` (`extension`),
  KEY `idx_status` (`status`),
  CONSTRAINT `fk_did_request_queue_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `extension_features` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `extension` varchar(10) NOT NULL,
  `user_id` int(11) DEFAULT NULL,
  `voicemail_enabled` tinyint(1) DEFAULT 1,
  `voicemail_pin` varchar(10) DEFAULT NULL,
  `email_notifications` tinyint(1) DEFAULT 1,
  `mastodon_notifications` tinyint(1) DEFAULT 0,
  `call_recording_enabled` tinyint(1) DEFAULT 1,
  `accessibility_enabled` tinyint(1) DEFAULT 1,
  `department` varchar(50) DEFAULT 'General',
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_extension` (`extension`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_extension_features_lookup` (`extension`,`voicemail_enabled`),
  CONSTRAINT `fk_extension_features_extension` FOREIGN KEY (`extension`) REFERENCES `extensions` (`extension_number`) ON DELETE CASCADE,
  CONSTRAINT `fk_extension_features_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `extension_phone_numbers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `extension_number` varchar(20) NOT NULL,
  `phone_number` varchar(20) NOT NULL,
  `carrier` varchar(50) NOT NULL,
  `carrier_gateway` varchar(100) NOT NULL,
  `sms_email` varchar(255) NOT NULL,
  `is_primary` tinyint(1) DEFAULT 1,
  `enabled` tinyint(1) DEFAULT 1,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_ext_phone` (`extension_number`,`phone_number`),
  KEY `idx_extension` (`extension_number`),
  KEY `idx_phone` (`phone_number`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Links extensions to phone numbers for SMS';
CREATE TABLE `extensions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `extension_number` varchar(10) NOT NULL,
  `display_name` varchar(100) NOT NULL,
  `email` varchar(100) DEFAULT NULL,
  `password_hash` varchar(255) NOT NULL,
  `user_id` int(11) DEFAULT NULL,
  `status` enum('active','inactive','suspended') DEFAULT 'active',
  `last_registered` datetime DEFAULT NULL,
  `registration_ip` varchar(45) DEFAULT NULL,
  `codec_preferences` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`codec_preferences`)),
  `call_forwarding` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`call_forwarding`)),
  `voicemail_enabled` tinyint(1) DEFAULT 1,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `extension_number` (`extension_number`),
  KEY `idx_extensions_number` (`extension_number`),
  KEY `idx_extensions_user` (`user_id`),
  CONSTRAINT `extensions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `fallback_hierarchy` (
  `id` varchar(255) NOT NULL,
  `primary_server` varchar(255) NOT NULL,
  `fallback_server` varchar(255) NOT NULL,
  `fallback_order` int(11) DEFAULT 1,
  `is_active` tinyint(1) DEFAULT 1,
  `created_at` datetime DEFAULT current_timestamp(),
  `last_tested` datetime DEFAULT NULL,
  `test_result` enum('success','failed','timeout') DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_primary` (`primary_server`),
  KEY `idx_fallback_order` (`fallback_order`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
CREATE TABLE `flexpbx_client_activity` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` varchar(64) NOT NULL,
  `activity_type` varchar(50) NOT NULL,
  `activity_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`activity_data`)),
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_client_id` (`client_id`),
  KEY `idx_activity_type` (`activity_type`),
  KEY `idx_created_at` (`created_at`),
  CONSTRAINT `flexpbx_client_activity_ibfk_1` FOREIGN KEY (`client_id`) REFERENCES `flexpbx_clients` (`client_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `flexpbx_client_modules` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` varchar(64) NOT NULL,
  `module_key` varchar(50) NOT NULL,
  `is_enabled` tinyint(1) DEFAULT 1,
  `auto_update` tinyint(1) DEFAULT 1,
  `installed_version` varchar(20) DEFAULT NULL,
  `config_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`config_data`)),
  `installed_at` datetime DEFAULT current_timestamp(),
  `last_updated` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_client_module` (`client_id`,`module_key`),
  KEY `idx_enabled` (`is_enabled`),
  KEY `idx_module` (`module_key`),
  CONSTRAINT `flexpbx_client_modules_ibfk_1` FOREIGN KEY (`client_id`) REFERENCES `flexpbx_clients` (`client_id`) ON DELETE CASCADE,
  CONSTRAINT `flexpbx_client_modules_ibfk_2` FOREIGN KEY (`module_key`) REFERENCES `flexpbx_modules` (`module_key`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `flexpbx_client_updates` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` varchar(64) NOT NULL,
  `update_version` varchar(20) NOT NULL,
  `update_status` enum('pending','downloading','installing','completed','failed','rolled_back') DEFAULT 'pending',
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `error_message` text DEFAULT NULL,
  `backup_file` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_client_id` (`client_id`),
  KEY `idx_status` (`update_status`),
  CONSTRAINT `flexpbx_client_updates_ibfk_1` FOREIGN KEY (`client_id`) REFERENCES `flexpbx_clients` (`client_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `flexpbx_clients` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` varchar(64) NOT NULL,
  `api_key` varchar(64) NOT NULL,
  `server_url` varchar(255) NOT NULL,
  `server_ip` varchar(45) DEFAULT NULL,
  `installation_type` enum('standalone','remote','hubnode','universal') DEFAULT 'universal',
  `flexpbx_version` varchar(20) DEFAULT NULL,
  `php_version` varchar(20) DEFAULT NULL,
  `distro_id` varchar(50) DEFAULT NULL,
  `distro_version` varchar(50) DEFAULT NULL,
  `admin_email` varchar(255) DEFAULT NULL,
  `admin_name` varchar(100) DEFAULT NULL,
  `status` enum('active','inactive','suspended','pending') DEFAULT 'pending',
  `last_check_in` datetime DEFAULT NULL,
  `last_update` datetime DEFAULT NULL,
  `features` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`features`)),
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `client_id` (`client_id`),
  UNIQUE KEY `api_key` (`api_key`),
  KEY `idx_client_id` (`client_id`),
  KEY `idx_api_key` (`api_key`),
  KEY `idx_status` (`status`),
  KEY `idx_last_check_in` (`last_check_in`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `flexpbx_modules` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `module_key` varchar(50) NOT NULL,
  `module_name` varchar(100) NOT NULL,
  `module_description` text DEFAULT NULL,
  `category` enum('core','integration','feature','addon') DEFAULT 'feature',
  `is_required` tinyint(1) DEFAULT 0,
  `version` varchar(20) DEFAULT NULL,
  `dependencies` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`dependencies`)),
  `install_script` varchar(255) DEFAULT NULL,
  `config_file` varchar(255) DEFAULT NULL,
  `database_schema` varchar(255) DEFAULT NULL,
  `status` enum('stable','beta','deprecated') DEFAULT 'stable',
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `module_key` (`module_key`),
  KEY `idx_category` (`category`),
  KEY `idx_required` (`is_required`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `flexpbx_update_releases` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `version` varchar(20) NOT NULL,
  `release_type` enum('major','minor','patch','hotfix') DEFAULT 'minor',
  `release_channel` enum('stable','beta','alpha','dev') DEFAULT 'stable',
  `release_notes` text DEFAULT NULL,
  `download_url` varchar(255) DEFAULT NULL,
  `file_size` bigint(20) DEFAULT NULL,
  `checksum_md5` varchar(32) DEFAULT NULL,
  `checksum_sha256` varchar(64) DEFAULT NULL,
  `min_version` varchar(20) DEFAULT NULL,
  `max_version` varchar(20) DEFAULT NULL,
  `required` tinyint(1) DEFAULT 0,
  `active` tinyint(1) DEFAULT 1,
  `released_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `version` (`version`),
  KEY `idx_version` (`version`),
  KEY `idx_channel` (`release_channel`),
  KEY `idx_active` (`active`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `modules` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `module_id` varchar(50) NOT NULL,
  `module_name` varchar(100) NOT NULL,
  `version` varchar(20) NOT NULL,
  `enabled` tinyint(1) DEFAULT 1,
  `installed_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `module_id` (`module_id`),
  KEY `idx_module_id` (`module_id`),
  KEY `idx_enabled` (`enabled`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `parking_history` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parking_lot_id` int(11) NOT NULL,
  `parking_space` varchar(10) NOT NULL,
  `parker_extension` varchar(20) DEFAULT NULL,
  `parker_callerid` varchar(100) DEFAULT NULL,
  `parked_callerid` varchar(100) DEFAULT NULL,
  `parked_number` varchar(50) DEFAULT NULL,
  `park_time` timestamp NULL DEFAULT current_timestamp(),
  `pickup_time` timestamp NULL DEFAULT NULL,
  `pickup_extension` varchar(20) DEFAULT NULL,
  `pickup_callerid` varchar(100) DEFAULT NULL,
  `timeout` tinyint(1) DEFAULT 0,
  `abandoned` tinyint(1) DEFAULT 0,
  `duration_parked` int(11) DEFAULT 0 COMMENT 'Seconds parked',
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `parking_lot_id` (`parking_lot_id`),
  KEY `park_time` (`park_time`),
  KEY `parking_space` (`parking_space`),
  CONSTRAINT `parking_history_ibfk_1` FOREIGN KEY (`parking_lot_id`) REFERENCES `parking_lots` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `parking_lots` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `park_ext` varchar(10) NOT NULL COMMENT 'Parking extension (*70)',
  `park_pos` varchar(50) NOT NULL COMMENT 'Parking positions (700-720)',
  `park_time` int(11) DEFAULT 300 COMMENT 'Timeout in seconds',
  `comeback_to_origin` tinyint(1) DEFAULT 1 COMMENT 'Return to parker if not picked up',
  `comeback_context` varchar(50) DEFAULT 'from-internal',
  `comeback_dialtime` int(11) DEFAULT 30 COMMENT 'Ring time on comeback',
  `parked_play` enum('caller','parked','both','no') DEFAULT 'caller' COMMENT 'Announce parking spot',
  `parked_music_class` varchar(50) DEFAULT 'default' COMMENT 'MOH class',
  `enabled` tinyint(1) DEFAULT 1,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `park_ext` (`park_ext`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `queue_members` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `queue_id` int(11) NOT NULL,
  `member_type` enum('extension','external') DEFAULT 'extension',
  `member_extension` varchar(50) NOT NULL COMMENT 'Extension number or external number',
  `member_name` varchar(100) DEFAULT NULL,
  `penalty` int(11) DEFAULT 0 COMMENT 'Priority (lower = higher priority)',
  `state_interface` varchar(100) DEFAULT NULL COMMENT 'Device to check for availability',
  `paused` tinyint(1) DEFAULT 0,
  `paused_reason` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `queue_member` (`queue_id`,`member_extension`),
  KEY `queue_id` (`queue_id`),
  CONSTRAINT `queue_members_ibfk_1` FOREIGN KEY (`queue_id`) REFERENCES `call_queues` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `queue_statistics` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `queue_id` int(11) NOT NULL,
  `date` date NOT NULL,
  `calls_offered` int(11) DEFAULT 0,
  `calls_answered` int(11) DEFAULT 0,
  `calls_abandoned` int(11) DEFAULT 0,
  `avg_wait_time` int(11) DEFAULT 0 COMMENT 'Seconds',
  `max_wait_time` int(11) DEFAULT 0 COMMENT 'Seconds',
  `service_level_met` int(11) DEFAULT 0,
  `service_level_percentage` decimal(5,2) DEFAULT 0.00,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `queue_date` (`queue_id`,`date`),
  CONSTRAINT `queue_statistics_ibfk_1` FOREIGN KEY (`queue_id`) REFERENCES `call_queues` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `ring_group_members` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ring_group_id` int(11) NOT NULL,
  `member_type` enum('extension','external') DEFAULT 'extension' COMMENT 'Internal extension or external number',
  `member_value` varchar(50) NOT NULL COMMENT 'Extension number or external phone number',
  `member_order` int(11) DEFAULT 0 COMMENT 'Order for hunt strategy',
  `enabled` tinyint(1) DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `idx_ring_group` (`ring_group_id`),
  CONSTRAINT `ring_group_members_ibfk_1` FOREIGN KEY (`ring_group_id`) REFERENCES `ring_groups` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Ring group member assignments';
CREATE TABLE `ring_groups` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `group_number` varchar(20) NOT NULL COMMENT 'Ring group extension number',
  `group_name` varchar(100) NOT NULL COMMENT 'Descriptive name',
  `strategy` enum('ringall','hunt','random','memoryhunt') DEFAULT 'ringall' COMMENT 'Ring strategy',
  `ring_time` int(11) DEFAULT 20 COMMENT 'Ring time in seconds',
  `skip_busy` tinyint(1) DEFAULT 1 COMMENT 'Skip busy members',
  `confirm_calls` tinyint(1) DEFAULT 0 COMMENT 'Require answer confirmation',
  `announcement` varchar(255) DEFAULT NULL COMMENT 'Announcement before ringing',
  `destination_type` enum('voicemail','extension','queue','ivr','hangup') DEFAULT 'voicemail' COMMENT 'No answer destination type',
  `destination_value` varchar(50) DEFAULT NULL COMMENT 'No answer destination value',
  `enabled` tinyint(1) DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `group_number` (`group_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Ring group configurations';
CREATE TABLE `sip_trunks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `provider` varchar(100) NOT NULL,
  `host` varchar(255) NOT NULL,
  `port` int(11) DEFAULT 5060,
  `username` varchar(100) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `codec_preferences` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`codec_preferences`)),
  `registration_required` tinyint(1) DEFAULT 1,
  `registration_status` enum('registered','unregistered','failed') DEFAULT 'unregistered',
  `last_registration` datetime DEFAULT NULL,
  `max_channels` int(11) DEFAULT 30,
  `current_channels` int(11) DEFAULT 0,
  `is_active` tinyint(1) DEFAULT 1,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `sms_messages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `extension_id` int(11) NOT NULL,
  `extension_number` varchar(20) NOT NULL,
  `phone_number` varchar(20) NOT NULL,
  `direction` enum('inbound','outbound') NOT NULL,
  `message_body` text NOT NULL,
  `from_number` varchar(20) NOT NULL,
  `to_number` varchar(20) NOT NULL,
  `carrier_gateway` varchar(100) DEFAULT NULL,
  `status` enum('pending','sent','delivered','failed','received') DEFAULT 'pending',
  `email_message_id` varchar(255) DEFAULT NULL,
  `sent_at` timestamp NULL DEFAULT NULL,
  `received_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_extension` (`extension_number`),
  KEY `idx_phone` (`phone_number`),
  KEY `idx_direction` (`direction`),
  KEY `idx_status` (`status`),
  KEY `idx_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='SMS messages sent/received via email gateway';
CREATE TABLE `sms_templates` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `extension_number` varchar(20) NOT NULL,
  `template_name` varchar(100) NOT NULL,
  `message_body` text NOT NULL,
  `is_shared` tinyint(1) DEFAULT 0,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_extension` (`extension_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='SMS message templates';
CREATE TABLE `system_config` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `config_key` varchar(100) NOT NULL,
  `config_value` text DEFAULT NULL,
  `config_type` enum('string','integer','boolean','json') DEFAULT 'string',
  `description` text DEFAULT NULL,
  `is_public` tinyint(1) DEFAULT 0,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `config_key` (`config_key`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `system_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `log_level` enum('DEBUG','INFO','WARNING','ERROR','CRITICAL') NOT NULL,
  `component` varchar(50) NOT NULL,
  `message` text NOT NULL,
  `user_id` int(11) DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `additional_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`additional_data`)),
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `idx_system_logs_time` (`created_at`),
  KEY `idx_system_logs_level` (`log_level`),
  CONSTRAINT `system_logs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `user_dids` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL,
  `extension` varchar(10) NOT NULL,
  `did_number` varchar(20) NOT NULL,
  `is_primary` tinyint(1) DEFAULT 1,
  `is_shared` tinyint(1) DEFAULT 0 COMMENT '1 if using shared main DID',
  `did_type` enum('own','shared','ported','new') DEFAULT 'shared',
  `assigned_date` timestamp NULL DEFAULT current_timestamp(),
  `notes` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_extension` (`extension`),
  KEY `idx_did_number` (`did_number`),
  KEY `idx_user_dids_lookup` (`extension`,`did_number`,`is_shared`),
  CONSTRAINT `fk_user_dids_extension` FOREIGN KEY (`extension`) REFERENCES `extensions` (`extension_number`) ON DELETE CASCADE,
  CONSTRAINT `fk_user_dids_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `user_notification_preferences` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `extension` varchar(10) DEFAULT NULL,
  `email_enabled` tinyint(1) DEFAULT 1,
  `notify_missed_calls` tinyint(1) DEFAULT 1,
  `notify_voicemail` tinyint(1) DEFAULT 1,
  `notify_fax` tinyint(1) DEFAULT 0,
  `notify_recordings` tinyint(1) DEFAULT 1,
  `mastodon_enabled` tinyint(1) DEFAULT 0,
  `mastodon_instance` varchar(100) DEFAULT NULL,
  `mastodon_access_token` varchar(255) DEFAULT NULL,
  `digest_enabled` tinyint(1) DEFAULT 0,
  `digest_frequency` enum('hourly','daily','weekly') DEFAULT 'daily',
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_user_id` (`user_id`),
  KEY `idx_extension` (`extension`),
  CONSTRAINT `fk_user_notification_preferences_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `user_signup_requests` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `full_name` varchar(100) NOT NULL,
  `requested_extension` varchar(10) DEFAULT NULL,
  `phone_number` varchar(20) DEFAULT NULL,
  `company_name` varchar(100) DEFAULT NULL,
  `status` enum('pending','approved','rejected') DEFAULT 'pending',
  `approval_notes` text DEFAULT NULL,
  `approved_by` int(11) DEFAULT NULL,
  `approved_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_username` (`username`),
  UNIQUE KEY `idx_email` (`email`),
  KEY `idx_status` (`status`),
  KEY `idx_approved_by` (`approved_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `full_name` varchar(100) NOT NULL,
  `role` enum('admin','user','operator') DEFAULT 'user',
  `is_active` tinyint(1) DEFAULT 1,
  `api_key` varchar(64) DEFAULT NULL,
  `pincode` varchar(6) DEFAULT NULL,
  `pincode_expires` datetime DEFAULT NULL,
  `last_login` datetime DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `api_key` (`api_key`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8mb4;
 1 AS `extension_number`,
  1 AS `display_name`,
  1 AS `email`,
  1 AS `status`,
  1 AS `last_registered`,
  1 AS `user_name`,
  1 AS `user_role` */;
SET character_set_client = @saved_cs_client;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8mb4;
 1 AS `call_date`,
  1 AS `call_direction`,
  1 AS `total_calls`,
  1 AS `total_duration`,
  1 AS `avg_duration`,
  1 AS `answered_calls` */;
SET character_set_client = @saved_cs_client;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8mb4;
 1 AS `device_name`,
  1 AS `device_type`,
  1 AS `last_connected`,
  1 AS `is_authorized`,
  1 AS `is_active`,
  1 AS `username`,
  1 AS `full_name`,
  1 AS `extension_number` */;
SET character_set_client = @saved_cs_client;
