<?php
/**
 * FlexPBX Server Configuration
 * Generated by Quick Installer on 2025-10-29 00:20:52
 */

return [
    // Database configuration
    'db_host' => 'localhost',
    'db_name' => 'flexpbxuser_flexpbx',
    'db_user' => 'flexpbxuser_flexpbxserver',
    'db_password' => 'DomDomRW93!',

    // API configuration
    'api_key' => 'flexpbx_api_8603f84b113de94f6876b99bd7003adf',
    'api_version' => '1.1.0',

    // Server configuration
    'server_name' => 'FlexPBX Remote Server',
    'max_connections_per_client' => 10,
    'default_connection_timeout' => 300,

    // Update server configuration
    'update_server' => [
        'enabled' => true,
        'check_interval' => 3600,
        'auto_download' => false,
        'download_path' => '/var/www/html/updates/',
        'supported_platforms' => ['darwin', 'win32', 'linux']
    ],

    // Security settings
    'security' => [
        'require_https' => false,
        'cors_enabled' => true,
        'rate_limiting' => [
            'enabled' => true,
            'max_requests_per_minute' => 60
        ]
    ],

    // Logging configuration
    'logging' => [
        'enabled' => true,
        'level' => 'INFO',
        'file' => dirname(__FILE__) . '/logs/connections.log',
        'max_size' => '100MB',
        'rotate' => true
    ]
];
?>